# This workflow builds project after a "Type Checking"

name: Building Project

on:
  workflow_run:
    workflows: ["Type Checking"]
    types: [completed]
    branches:
      - main
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x" # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        if: success()
        run: npm run build-ts

      - name: Run Project
        if: success()
        run: npm run index

      - name: Build with PKG
        if: success()
        run: npm run build-pkg

      - name: Upload as Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: metal
          path: build/metal.exe
